import type { User, Schedule, MaintenanceTicket, ScheduleTrade, UBS } from "./types";

export const INITIAL_UBSS: UBS[] = [
  {
    id: "UBS-01-CENTRO",
    nome: "UBS Central Dr. Paulo Silva",
    bairro: "Centro",
    cadeirasOdontologicas: 4,
    telefone: "(11) 3241-1000",
  },
  {
    id: "UBS-02-VILA-MARIANA",
    nome: "UBS Vila Mariana",
    bairro: "Vila Mariana",
    cadeirasOdontologicas: 3,
    telefone: "(11) 3241-2000",
  },
  {
    id: "UBS-03-JARDINS",
    nome: "UBS Jardins da Serra",
    bairro: "Jardins",
    cadeirasOdontologicas: 3,
    telefone: "(11) 3241-3000",
  },
  {
    id: "UBS-04-SANTA-CECILIA",
    nome: "UBS Santa Cecília",
    bairro: "Santa Cecília",
    cadeirasOdontologicas: 2,
    telefone: "(11) 3241-4000",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr_admin_01",
    nome: "Dra. Silvana Rocha",
    cargo: "Admin",
    UBS_id: "UBS-01-CENTRO",
    ubsNome: "Coordenação Geral SMS",
    fcmToken: "fcm_token_admin_silvana",
    email: "silvana.rocha@saude.gov.br",
    croOuRegistro: "CRO-SP 72.109 / Gestão",
  },
  {
    id: "usr_dent_01",
    nome: "Dr. Lucas Mendes",
    cargo: "Dentista",
    UBS_id: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    fcmToken: "fcm_token_dent_lucas",
    email: "lucas.mendes@saude.gov.br",
    croOuRegistro: "CRO-SP 98.412",
  },
  {
    id: "usr_dent_02",
    nome: "Dra. Camila Nogueira",
    cargo: "Dentista",
    UBS_id: "UBS-02-VILA-MARIANA",
    ubsNome: "UBS Vila Mariana",
    fcmToken: "fcm_token_dent_camila",
    email: "camila.nogueira@saude.gov.br",
    croOuRegistro: "CRO-SP 104.221",
  },
  {
    id: "usr_dent_03",
    nome: "Dr. Rafael Albuquerque",
    cargo: "Dentista",
    UBS_id: "UBS-03-JARDINS",
    ubsNome: "UBS Jardins da Serra",
    fcmToken: "fcm_token_dent_rafael",
    email: "rafael.albuquerque@saude.gov.br",
    croOuRegistro: "CRO-SP 89.155",
  },
  {
    id: "usr_dent_04",
    nome: "Dra. Mariana Costa",
    cargo: "Dentista",
    UBS_id: "UBS-04-SANTA-CECILIA",
    ubsNome: "UBS Santa Cecília",
    fcmToken: "fcm_token_dent_mariana",
    email: "mariana.costa@saude.gov.br",
    croOuRegistro: "CRO-SP 112.980",
  },
  {
    id: "usr_asb_01",
    nome: "Beatriz Lima",
    cargo: "ASB",
    UBS_id: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    fcmToken: "fcm_token_asb_beatriz",
    email: "beatriz.lima@saude.gov.br",
    croOuRegistro: "ASB-SP 43.120",
  },
  {
    id: "usr_tec_01",
    nome: "Marcos Rocha",
    cargo: "Técnico",
    UBS_id: "UBS-01-CENTRO",
    ubsNome: "Oficina Central de Engenharia Clínica",
    fcmToken: "fcm_token_tec_marcos",
    email: "marcos.rocha@saude.gov.br",
    croOuRegistro: "CFT-SP 55.409",
  },
  {
    id: "usr_tec_02",
    nome: "Carlos Eduardo",
    cargo: "Técnico",
    UBS_id: "UBS-02-VILA-MARIANA",
    ubsNome: "Oficina Central de Engenharia Clínica",
    fcmToken: "fcm_token_tec_carlos",
    email: "carlos.eduardo@saude.gov.br",
    croOuRegistro: "CFT-SP 49.310",
  },
];

// Escalas da semana de trabalho municipal
export const INITIAL_SCHEDULES: Schedule[] = [
  // Segunda-feira (2026-09-21)
  {
    id: "sch_01",
    userId: "usr_dent_01",
    userNome: "Dr. Lucas Mendes",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-21",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },
  {
    id: "sch_02",
    userId: "usr_dent_02",
    userNome: "Dra. Camila Nogueira",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-21",
    turno: "Tarde",
    horario: "13:00 - 19:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },
  {
    id: "sch_03",
    userId: "usr_dent_03",
    userNome: "Dr. Rafael Albuquerque",
    userCargo: "Dentista",
    ubsId: "UBS-02-VILA-MARIANA",
    ubsNome: "UBS Vila Mariana",
    data: "2026-09-21",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 02",
    status: "confirmado",
  },

  // Terça-feira (2026-09-22)
  {
    id: "sch_04",
    userId: "usr_dent_01",
    userNome: "Dr. Lucas Mendes",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-22",
    turno: "Tarde",
    horario: "13:00 - 19:00",
    consultorio: "Consultório 01",
    status: "pendente_troca",
  },
  {
    id: "sch_05",
    userId: "usr_dent_04",
    userNome: "Dra. Mariana Costa",
    userCargo: "Dentista",
    ubsId: "UBS-03-JARDINS",
    ubsNome: "UBS Jardins da Serra",
    data: "2026-09-22",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },

  // Quarta-feira (2026-09-23)
  {
    id: "sch_06",
    userId: "usr_dent_02",
    userNome: "Dra. Camila Nogueira",
    userCargo: "Dentista",
    ubsId: "UBS-02-VILA-MARIANA",
    ubsNome: "UBS Vila Mariana",
    data: "2026-09-23",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },
  {
    id: "sch_07",
    userId: "usr_dent_03",
    userNome: "Dr. Rafael Albuquerque",
    userCargo: "Dentista",
    ubsId: "UBS-03-JARDINS",
    ubsNome: "UBS Jardins da Serra",
    data: "2026-09-23",
    turno: "Tarde",
    horario: "13:00 - 19:00",
    consultorio: "Consultório 02",
    status: "confirmado",
  },

  // Quinta-feira (2026-09-24)
  {
    id: "sch_08",
    userId: "usr_dent_01",
    userNome: "Dr. Lucas Mendes",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-24",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 02",
    status: "confirmado",
  },
  {
    id: "sch_09",
    userId: "usr_dent_04",
    userNome: "Dra. Mariana Costa",
    userCargo: "Dentista",
    ubsId: "UBS-04-SANTA-CECILIA",
    ubsNome: "UBS Santa Cecília",
    data: "2026-09-24",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },

  // Sexta-feira (2026-09-25)
  {
    id: "sch_10",
    userId: "usr_dent_01",
    userNome: "Dr. Lucas Mendes",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-25",
    turno: "Manhã",
    horario: "07:00 - 13:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },
  {
    id: "sch_11",
    userId: "usr_dent_02",
    userNome: "Dra. Camila Nogueira",
    userCargo: "Dentista",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    data: "2026-09-25",
    turno: "Tarde",
    horario: "13:00 - 19:00",
    consultorio: "Consultório 01",
    status: "confirmado",
  },
];

// Tickets de manutenção odontológica
export const INITIAL_TICKETS: MaintenanceTicket[] = [
  {
    id: "tkt_01",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    equipamento: "Autoclave Hospitalar Cristófoli 21L",
    nivelPrioridade: "Alta",
    descricao: "Autoclave não atinge pressão de esterilização (1.5 kgf/cm²). Apresenta apito de erro E03 e escape de vapor pela borracha de vedação.",
    fotoUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=80",
    status: "aberto",
    criadoEm: "2026-09-18T08:30:00Z",
    criadoPor: "usr_dent_01",
    solicitanteNome: "Dr. Lucas Mendes",
    atribuidoA: null,
    tecnicoNome: null,
    diagnosticoIA: {
      equipamentoIdentificado: "Autoclave Hospitalar a Vapor",
      nivelUrgencia: "Alta",
      justificativaImpacto: "A autoclave é essencial para o fluxo de biossegurança. Sem ela, todos os kits cirúrgicos e clínicos ficam indisponíveis, paralisando a UBS em 24h.",
      sugestaoDiagnostico: "Substituir guarnição de silicone da porta, calibrar sensor PT-100 de temperatura e inspecionar válvula de segurança contra sobrepressão.",
    },
  },
  {
    id: "tkt_02",
    ubsId: "UBS-02-VILA-MARIANA",
    ubsNome: "UBS Vila Mariana",
    equipamento: "Bomba de Vácuo / Sugador Cirúrgico",
    nivelPrioridade: "Alta",
    descricao: "Cadeira odontológica 02 sem sucção na ponta cirúrgica. Motor da bomba faz ruído agudo intermitente e aquece excessivamente.",
    fotoUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80",
    status: "em_atendimento",
    criadoEm: "2026-09-18T09:15:00Z",
    criadoPor: "usr_dent_02",
    solicitanteNome: "Dra. Camila Nogueira",
    atribuidoA: "usr_tec_01",
    tecnicoNome: "Marcos Rocha",
    diagnosticoIA: {
      equipamentoIdentificado: "Bomba de Vácuo Odontológica",
      nivelUrgencia: "Alta",
      justificativaImpacto: "A ausência de sucção de alta potência impede procedimentos cirúrgicos e exodontias, aumentando a dispersão de aerossóis na sala.",
      sugestaoDiagnostico: "Desobstruir filtro coletor de amálgama/detritos orgânicos, verificar rolamentos do rotor do motor elétrico e vedação dos canos de PVC de retorno.",
    },
  },
  {
    id: "tkt_03",
    ubsId: "UBS-03-JARDINS",
    ubsNome: "UBS Jardins da Serra",
    equipamento: "Aparelho de Raio-X Periapical de Coluna",
    nivelPrioridade: "Média",
    descricao: "Braço pantográfico do Raio-X está cedendo e não fixa na posição vertical. Disparador eletrônico funcionando normalmente.",
    fotoUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80",
    status: "aberto",
    criadoEm: "2026-09-17T14:20:00Z",
    criadoPor: "usr_dent_03",
    solicitanteNome: "Dr. Rafael Albuquerque",
    atribuidoA: null,
    tecnicoNome: null,
    diagnosticoIA: {
      equipamentoIdentificado: "Raio-X Periapical Odontológico",
      nivelUrgencia: "Média",
      justificativaImpacto: "O deslocamento do cabeçote gera distorção nas tomadas radiográficas periapicais, necessitando repetições de exposição à radiação ionizante.",
      sugestaoDiagnostico: "Ajustar fricção mecânica das molas internas do braço articulado e verificar parafusos de travamento da base de fixação na parede/coluna.",
    },
  },
  {
    id: "tkt_04",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    equipamento: "Fotopolimerizador LED Sem Fio",
    nivelPrioridade: "Média",
    descricao: "Bateria descarregando com menos de 3 restaurações. Teste de fotopolimerização com radiômetro apresentou queda de 1200 para 450 mW/cm².",
    fotoUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
    status: "concluido",
    criadoEm: "2026-09-16T11:00:00Z",
    criadoPor: "usr_dent_01",
    solicitanteNome: "Dr. Lucas Mendes",
    atribuidoA: "usr_tec_02",
    tecnicoNome: "Carlos Eduardo",
    diagnosticoIA: {
      equipamentoIdentificado: "Fotopolimerizador LED Odontológico",
      nivelUrgencia: "Média",
      justificativaImpacto: "Intensidade luminosa abaixo do mínimo compromete a polimerização da resina composta, causando falha adesiva precoce nas restaurações.",
      sugestaoDiagnostico: "Substituição da célula de íon-lítio 18650 e limpeza da lente óptica da ponteira com álcool isopropílico.",
    },
    relatorioTecnico: "Bateria substituída por peça original e ponteira higienizada. Aferido no radiômetro: 1.350 mW/cm². Equipamento liberado para uso.",
    concluidoEm: "2026-09-17T16:00:00Z",
  },
];

// Trocas de escala
export const INITIAL_TRADES: ScheduleTrade[] = [
  {
    id: "trd_01",
    solicitanteId: "usr_dent_01",
    solicitanteNome: "Dr. Lucas Mendes",
    substitutoId: "usr_dent_02",
    substitutoNome: "Dra. Camila Nogueira",
    scheduleId: "sch_04",
    dataEscala: "2026-09-22",
    turnoEscala: "Tarde",
    ubsId: "UBS-01-CENTRO",
    ubsNome: "UBS Central Dr. Paulo Silva",
    motivo: "Participação em congresso municipal de cirurgia bucomaxilofacial com dispensa funcional solicitada.",
    status: "aguardando_aprovacao_admin",
    criadoEm: "2026-09-18T10:00:00Z",
  },
];

// Equipamentos predefinidos para testes rápidos no formulário do Dentista
export const SAMPLE_EQUIPMENT_PRESETS = [
  {
    nome: "Autoclave Cristófoli 21L",
    descricao: "Vazamento contínuo de vapor na porta e erro de pressão E04 durante o ciclo de 134°C.",
    fotoUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Cadeira Odontológica Gnatus",
    descricao: "Cadeira travada na posição reclinada; pedal de acionamento não responde e motor de elevação hidráulica não dá partida.",
    fotoUrl: "https://images.unsplash.com/photo-1629909615184-74f495363b67?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Compressor Odontológico Silencioso",
    descricao: "Compressor desarmando disjuntor do quadro geral após 30 segundos de funcionamento. Cheiro de aquecimento de fiação.",
    fotoUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80",
  },
  {
    nome: "Sugador Cirúrgico / Bomba Vácuo",
    descricao: "Perda completa de pressão de sucção durante extração de terceiro molar.",
    fotoUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80",
  },
];
